version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gradle
    directory: /android/NexusRemote
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
  - package-ecosystem: gradle
    directory: /android/NexusConsole
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
