const test = require('node:test');
const assert = require('node:assert/strict');
const { AIProviderRegistry } = require('../src/ai/ai-provider-registry');
const { AIRuntime } = require('../src/ai/ai-runtime');
const { MockProvider } = require('../src/ai/providers/mock-provider');
const { AI_ERROR_CODES } = require('../src/ai/ai-errors');

test('registry registra, crea e lista provider validati', () => { const registry = new AIProviderRegistry().register('mock', (config) => new MockProvider(config)); assert.equal(registry.has('mock'), true); assert.deepEqual(registry.listProviders(), ['mock']); assert.equal(registry.create('mock', {}).name, 'mock'); assert.throws(() => registry.register('mock', () => new MockProvider()), /già registrato/); });
test('runtime inoltra health, modelli, chat ed embedding al provider attivo', async () => { const registry = new AIProviderRegistry().register('mock', (config) => new MockProvider(config)); const runtime = new AIRuntime({ registry }); await runtime.initialize({ provider: 'mock', chatModel: 'mock-chat' }); assert.equal((await runtime.health()).status, 'ready'); assert.equal((await runtime.listModels()).length, 1); const chat = await runtime.chat({ requestId: 'chat-1', mode: 'quick', messages: [{ role: 'user', content: 'ciao' }] }); assert.equal(chat.message.content, 'mock:ciao'); const embedding = await runtime.embed(['a', 'bb']); assert.equal(embedding.vectors.length, 2); assert.equal(runtime.requests.size, 0); await runtime.shutdown(); });
test('runtime impedisce collisioni e cancella soltanto la richiesta indicata', async () => { let started; const gate = new Promise((resolve) => { started = resolve; }); const provider = new MockProvider(); provider.chat = async (request) => { started(); await new Promise((resolve, reject) => { request.signal.addEventListener('abort', () => reject(Object.assign(new Error('aborted'), { name: 'AbortError' })), { once: true }); }); }; const registry = new AIProviderRegistry().register('slow', () => provider); const runtime = new AIRuntime({ registry }); await runtime.initialize({ provider: 'slow' }); const pending = runtime.chat({ requestId: 'slow-1', mode: 'quick', messages: [{ role: 'user', content: 'wait' }] }); await gate; assert.equal(runtime.cancel('slow-1'), true); await assert.rejects(pending, (error) => error.code === AI_ERROR_CODES.REQUEST_CANCELLED); assert.equal(runtime.requests.size, 0); });
test('MockProvider produce streaming ed embedding deterministici senza fallback produzione', async () => { const provider = new MockProvider(); const tokens = []; const result = await provider.streamChat({ requestId: 'stream-1', mode: 'quick', messages: [{ role: 'user', content: 'x' }] }, { onToken: (token) => tokens.push(token) }); assert.deepEqual(tokens, ['mock:', 'x']); assert.equal(result.message.content, 'mock:x'); assert.deepEqual((await provider.embed('abc')).vectors, [[3, 294, 1]]); });
