const test = require('node:test');
const assert = require('node:assert/strict');
const http = require('node:http');
const { OllamaProvider } = require('../src/ai/providers/ollama-provider');
const { AI_ERROR_CODES } = require('../src/ai/ai-errors');

async function server(handler) { const instance = http.createServer(handler); await new Promise((resolve) => instance.listen(0, '127.0.0.1', resolve)); return { url: `http://127.0.0.1:${instance.address().port}`, close: () => new Promise((resolve) => instance.close(resolve)) }; }
function json(response, data, status = 200) { response.writeHead(status, { 'Content-Type': 'application/json' }); response.end(JSON.stringify(data)); }
async function providerFor(url, options = {}) { const provider = new OllamaProvider({ provider: 'ollama', ollama: { baseUrl: url, timeoutMs: options.timeoutMs || 1000 }, chatModel: options.chatModel ?? 'qwen:test', embeddingModel: options.embeddingModel ?? 'embed:test' }); await provider.initialize({ provider: 'ollama', ollama: { baseUrl: url, timeoutMs: options.timeoutMs || 1000 }, chatModel: options.chatModel ?? 'qwen:test', embeddingModel: options.embeddingModel ?? 'embed:test' }); return provider; }

test('health distingue READY, nessun modello e modello selezionato assente', async () => { let models = [{ name: 'qwen:test', model: 'qwen:test', size: 42, modified_at: '2026-01-01T00:00:00Z' }]; const local = await server((request, response) => request.url === '/api/version' ? json(response, { version: '1.2.3' }) : json(response, { models })); try { const provider = await providerFor(local.url); assert.equal((await provider.health()).status, 'ready'); models = []; assert.equal((await provider.health()).status, 'degraded'); models = [{ name: 'other', model: 'other' }]; assert.equal((await provider.health()).error.code, AI_ERROR_CODES.MODEL_NOT_FOUND); } finally { await local.close(); } });
test('health distingue OFFLINE, timeout e risposta fondamentale invalida', async () => { const timeoutServer = await server((_request, response) => setTimeout(() => json(response, { models: [] }), 350)); const timeoutProvider = await providerFor(timeoutServer.url, { timeoutMs: 250 }); assert.equal((await timeoutProvider.health()).status, 'offline'); await timeoutServer.close(); const invalid = await server((_request, response) => json(response, { nope: true })); try { const provider = await providerFor(invalid.url); assert.equal((await provider.health()).status, 'error'); } finally { await invalid.close(); } });
test('listModels normalizza descrittori e setModel valida esistenza', async () => { const local = await server((_request, response) => json(response, { models: [{ name: 'alpha', model: 'alpha', size: 99 }] })); try { const provider = await providerFor(local.url); const models = await provider.listModels(); assert.equal(models[0].provider, 'ollama'); assert.equal(models[0].capabilities.streaming, true); await assert.rejects(provider.setModel('missing'), (error) => error.code === AI_ERROR_CODES.MODEL_NOT_FOUND); assert.equal((await provider.setModel('alpha')).id, 'alpha'); } finally { await local.close(); } });
test('chat normalizza risposta, usage e modello', async () => { const local = await server((_request, response) => json(response, { model: 'qwen:test', message: { role: 'assistant', content: 'ok' }, done: true, done_reason: 'stop', prompt_eval_count: 2, eval_count: 3 })); try { const provider = await providerFor(local.url); const result = await provider.chat({ requestId: 'c1', mode: 'quick', messages: [{ role: 'user', content: 'hi' }] }); assert.equal(result.message.content, 'ok'); assert.equal(result.usage.totalTokens, 5); } finally { await local.close(); } });
test('streaming gestisce chunk spezzati e ultima riga senza newline', async () => { const local = await server((_request, response) => { response.writeHead(200, { 'Content-Type': 'application/x-ndjson' }); response.write('{"model":"qwen:test","message":{"content":"hel'); setTimeout(() => { response.write('lo"},"done":false}\n'); response.end('{"model":"qwen:test","message":{"content":"!"},"done":true,"done_reason":"stop"}'); }, 5); }); try { const provider = await providerFor(local.url); const tokens = []; let completed = 0; const result = await provider.streamChat({ requestId: 's1', mode: 'quick', messages: [{ role: 'user', content: 'hi' }] }, { onToken: (token) => tokens.push(token), onComplete: () => completed++ }); assert.deepEqual(tokens, ['hello', '!']); assert.equal(result.message.content, 'hello!'); assert.equal(completed, 1); } finally { await local.close(); } });
test('streaming invalido emette onError una sola volta', async () => { const local = await server((_request, response) => { response.writeHead(200); response.end('{bad}\n'); }); try { const provider = await providerFor(local.url); let errors = 0; await assert.rejects(provider.streamChat({ requestId: 's2', mode: 'quick', messages: [{ role: 'user', content: 'hi' }] }, { onError: () => errors++ }), (error) => error.code === AI_ERROR_CODES.STREAM_INTERRUPTED); assert.equal(errors, 1); } finally { await local.close(); } });
test('embed accetta batch e valida vettori', async () => { const local = await server((_request, response) => json(response, { model: 'embed:test', embeddings: [[1, 0], [0, 1]], prompt_eval_count: 4 })); try { const provider = await providerFor(local.url); const result = await provider.embed(['a', 'b']); assert.equal(result.dimensions, 2); assert.equal(result.vectors.length, 2); } finally { await local.close(); } });
