/**
 * @module preload
 * @description Bridge sandboxed che espone al renderer soltanto le capability IPC autorizzate.
 */
const { contextBridge, ipcRenderer } = require('electron');

// #region 01 — Canali duplicati intenzionalmente per la sandbox

// Un preload sandboxed dispone del require limitato di Electron e non può
// caricare moduli locali. Questi nomi rispecchiano il contratto autoritativo
// validato nel main process da application/ipc-contracts.js.
const CHANNELS = Object.freeze({
  bootstrap: 'nexus:bootstrap',
  settings: 'nexus:settings',
  reindex: 'nexus:reindex',
  listModels: 'nexus:list-models',
  modelBenchmark: 'nexus:model-benchmark',
  cancel: 'nexus:cancel',
  copy: 'nexus:copy',
  openExternal: 'nexus:open-external',
  openNote: 'nexus:open-note',
  chat: 'nexus:chat',
  health: 'nexus:ai-health',
  diagnostics: 'nexus:diagnostics',
  setModel: 'nexus:set-model',
  streamChat: 'nexus:stream-chat',
  streamEvent: 'nexus:stream-event',
  embed: 'nexus:embed',
  agentCapabilities: 'nexus:agent-capabilities',
  agentPlan: 'nexus:agent-plan',
  agentExecute: 'nexus:agent-execute',
  workflowCreate: 'nexus:workflow-create',
  workflowNext: 'nexus:workflow-next',
  workflowDecide: 'nexus:workflow-decide',
  workflowCancel: 'nexus:workflow-cancel',
  workflowStatus: 'nexus:workflow-status',
  voiceCapabilities: 'nexus:voice-capabilities',
  voiceDevices: 'nexus:voice-devices',
  voiceTranscribe: 'nexus:voice-transcribe',
  voiceTranscribeAudio: 'nexus:voice-transcribe-audio',
  voiceActivity: 'nexus:voice-activity',
  voicePartial: 'nexus:voice-partial',
  voiceStop: 'nexus:voice-stop',
  voiceFinish: 'nexus:voice-finish',
  neuralVoiceCapabilities: 'nexus:neural-voice-capabilities',
  neuralVoiceSpeak: 'nexus:neural-voice-speak',
  neuralVoiceStop: 'nexus:neural-voice-stop',
  knowledgeList: 'nexus:knowledge-list',
  knowledgeRead: 'nexus:knowledge-read',
  trainingExample: 'nexus:training-example',
  trainingStats: 'nexus:training-stats',
  trainingEvaluation: 'nexus:training-evaluation',
  trainingClear: 'nexus:training-clear',
  memoryList: 'nexus:memory-list',
  memoryForget: 'nexus:memory-forget',
  responseCacheStats: 'nexus:response-cache-stats',
  responseCacheClear: 'nexus:response-cache-clear',
  backupExport: 'nexus:backup-export',
  backupImport: 'nexus:backup-import',
  actionHistory: 'nexus:action-history',
  actionUndo: 'nexus:action-undo',
  windowCompact: 'nexus:window-compact',
  presenceSync: 'nexus:presence-sync',
  provisioningStatus: 'nexus:provisioning-status',
  provisioningStart: 'nexus:provisioning-start',
  provisioningCancel: 'nexus:provisioning-cancel',
  provisioningEvent: 'nexus:provisioning-event',
  provisioningEngine: 'nexus:provisioning-engine',
  voiceSettings: 'nexus:voice-settings',
  selectAttachments: 'nexus:select-attachments',
  workspaceGet: 'nexus:workspace-get',
  workspaceSelect: 'nexus:workspace-select',
  workspaceClear: 'nexus:workspace-clear',
  historyList: 'nexus:history-list',
  historySave: 'nexus:history-save',
  historyRemove: 'nexus:history-remove',
  historyImport: 'nexus:history-import',
  remoteStatus: 'nexus:remote-status',
  remoteConfigure: 'nexus:remote-configure',
  remotePair: 'nexus:remote-pair',
  remoteRevoke: 'nexus:remote-revoke',
  remoteSetup: 'nexus:remote-setup',
  startupStatus: 'nexus:startup-status',
  startupConfigure: 'nexus:startup-configure',
  updateStatus: 'nexus:update-status',
  updateCheck: 'nexus:update-check',
  updateInstall: 'nexus:update-install',
  updateEvent: 'nexus:update-event',
  proactiveEvent: 'nexus:proactive-event',
  wakeWordActivation: 'nexus:wake-word-activation'
});

// #endregion

// #region 02 — Bridge renderer

// API minima e intenzionale: il renderer non vede filesystem, shell o ipcRenderer.
// Ogni argomento sarà nuovamente validato nel processo principale.
contextBridge.exposeInMainWorld('nexus', {
  bootstrap: () => ipcRenderer.invoke(CHANNELS.bootstrap),
  chat: (payload) => ipcRenderer.invoke(CHANNELS.chat, payload),
  reindex: () => ipcRenderer.invoke(CHANNELS.reindex),
  listModels: () => ipcRenderer.invoke(CHANNELS.listModels),
  benchmarkModels: () => ipcRenderer.invoke(CHANNELS.modelBenchmark),
  cancel: (requestId) => ipcRenderer.invoke(CHANNELS.cancel, requestId),
  copyText: (text) => ipcRenderer.invoke(CHANNELS.copy, text),
  openExternal: (url) => ipcRenderer.invoke(CHANNELS.openExternal, url),
  saveSettings: (settings) => ipcRenderer.invoke(CHANNELS.settings, settings),
  openNote: (relativePath) => ipcRenderer.invoke(CHANNELS.openNote, relativePath),
  health: () => ipcRenderer.invoke(CHANNELS.health),
  diagnostics: () => ipcRenderer.invoke(CHANNELS.diagnostics),
  setModel: (model) => ipcRenderer.invoke(CHANNELS.setModel, model),
  streamChat: (payload) => ipcRenderer.invoke(CHANNELS.streamChat, payload),
  onStreamEvent: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on(CHANNELS.streamEvent, handler); return () => ipcRenderer.removeListener(CHANNELS.streamEvent, handler); },
  embed: (input, options) => ipcRenderer.invoke(CHANNELS.embed, { input, ...options }),
  listAgentCapabilities: () => ipcRenderer.invoke(CHANNELS.agentCapabilities),
  planAction: (instruction) => ipcRenderer.invoke(CHANNELS.agentPlan, instruction),
  executeAction: (ticketId, approved) => ipcRenderer.invoke(CHANNELS.agentExecute, { ticketId, approved }),
  createWorkflow: (workflow) => ipcRenderer.invoke(CHANNELS.workflowCreate, workflow),
  nextWorkflowStep: (workflowId) => ipcRenderer.invoke(CHANNELS.workflowNext, { workflowId }),
  decideWorkflowStep: (workflowId, ticketId, approved) => ipcRenderer.invoke(CHANNELS.workflowDecide, { workflowId, ticketId, approved }),
  cancelWorkflow: (workflowId) => ipcRenderer.invoke(CHANNELS.workflowCancel, { workflowId }),
  workflowStatus: (workflowId) => ipcRenderer.invoke(CHANNELS.workflowStatus, { workflowId }),
  voiceCapabilities: () => ipcRenderer.invoke(CHANNELS.voiceCapabilities),
  voiceDevices: () => ipcRenderer.invoke(CHANNELS.voiceDevices),
  transcribeVoice: (options) => ipcRenderer.invoke(CHANNELS.voiceTranscribe, options),
  transcribeVoiceAudio: (audio) => ipcRenderer.invoke(CHANNELS.voiceTranscribeAudio, audio),
  onVoiceActivity: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on(CHANNELS.voiceActivity, handler); return () => ipcRenderer.removeListener(CHANNELS.voiceActivity, handler); },
  onVoicePartial: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on(CHANNELS.voicePartial, handler); return () => ipcRenderer.removeListener(CHANNELS.voicePartial, handler); },
  stopVoice: () => ipcRenderer.invoke(CHANNELS.voiceStop),
  finishVoice: () => ipcRenderer.invoke(CHANNELS.voiceFinish),
  neuralVoiceCapabilities: () => ipcRenderer.invoke(CHANNELS.neuralVoiceCapabilities),
  synthesizeVoice: (options) => ipcRenderer.invoke(CHANNELS.neuralVoiceSpeak, options),
  stopSpeaking: () => ipcRenderer.invoke(CHANNELS.neuralVoiceStop),
  listKnowledgeNotes: () => ipcRenderer.invoke(CHANNELS.knowledgeList),
  readKnowledgeNote: (relativePath) => ipcRenderer.invoke(CHANNELS.knowledgeRead, relativePath),
  saveTrainingExample: (example) => ipcRenderer.invoke(CHANNELS.trainingExample, example),
  trainingStats: () => ipcRenderer.invoke(CHANNELS.trainingStats),
  trainingEvaluation: () => ipcRenderer.invoke(CHANNELS.trainingEvaluation),
  clearTrainingExamples: () => ipcRenderer.invoke(CHANNELS.trainingClear),
  listMemories: () => ipcRenderer.invoke(CHANNELS.memoryList),
  forgetMemory: (id) => ipcRenderer.invoke(CHANNELS.memoryForget, id),
  responseCacheStats: () => ipcRenderer.invoke(CHANNELS.responseCacheStats),
  clearResponseCache: () => ipcRenderer.invoke(CHANNELS.responseCacheClear),
  exportPersonalData: (clientData, passphrase) => ipcRenderer.invoke(CHANNELS.backupExport, { clientData, passphrase }),
  importPersonalData: (passphrase) => ipcRenderer.invoke(CHANNELS.backupImport, { passphrase }),
  actionHistory: () => ipcRenderer.invoke(CHANNELS.actionHistory),
  undoLastAction: () => ipcRenderer.invoke(CHANNELS.actionUndo),
  setCompactWindow: (enabled) => ipcRenderer.invoke(CHANNELS.windowCompact, enabled),
  syncPresence: (snapshot) => ipcRenderer.invoke(CHANNELS.presenceSync, snapshot),
  provisioningStatus: () => ipcRenderer.invoke(CHANNELS.provisioningStatus),
  startProvisioning: (profile) => ipcRenderer.invoke(CHANNELS.provisioningStart, profile),
  cancelProvisioning: () => ipcRenderer.invoke(CHANNELS.provisioningCancel),
  onProvisioningEvent: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on(CHANNELS.provisioningEvent, handler); return () => ipcRenderer.removeListener(CHANNELS.provisioningEvent, handler); },
  openEngineInstaller: () => ipcRenderer.invoke(CHANNELS.provisioningEngine),
  openVoiceSettings: () => ipcRenderer.invoke(CHANNELS.voiceSettings),
  selectAttachments: () => ipcRenderer.invoke(CHANNELS.selectAttachments),
  getWorkspace: () => ipcRenderer.invoke(CHANNELS.workspaceGet),
  selectWorkspace: () => ipcRenderer.invoke(CHANNELS.workspaceSelect),
  clearWorkspace: () => ipcRenderer.invoke(CHANNELS.workspaceClear),
  listConversationHistory: () => ipcRenderer.invoke(CHANNELS.historyList),
  saveConversationHistory: (record) => ipcRenderer.invoke(CHANNELS.historySave, record),
  removeConversationHistory: (id) => ipcRenderer.invoke(CHANNELS.historyRemove, id),
  importConversationHistory: (records) => ipcRenderer.invoke(CHANNELS.historyImport, records),
  remoteStatus: () => ipcRenderer.invoke(CHANNELS.remoteStatus),
  configureRemote: (options) => ipcRenderer.invoke(CHANNELS.remoteConfigure, options),
  createRemotePairing: () => ipcRenderer.invoke(CHANNELS.remotePair),
  revokeRemoteDevice: (id) => ipcRenderer.invoke(CHANNELS.remoteRevoke, id),
  setupRemoteAccess: (mode) => ipcRenderer.invoke(CHANNELS.remoteSetup, mode),
  startupStatus: () => ipcRenderer.invoke(CHANNELS.startupStatus),
  configureStartup: (enabled) => ipcRenderer.invoke(CHANNELS.startupConfigure, enabled),
  updateStatus: () => ipcRenderer.invoke(CHANNELS.updateStatus),
  checkForUpdates: () => ipcRenderer.invoke(CHANNELS.updateCheck),
  installUpdate: () => ipcRenderer.invoke(CHANNELS.updateInstall),
  onUpdateEvent: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on(CHANNELS.updateEvent, handler); return () => ipcRenderer.removeListener(CHANNELS.updateEvent, handler); },
  onProactiveEvent: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on(CHANNELS.proactiveEvent, handler); return () => ipcRenderer.removeListener(CHANNELS.proactiveEvent, handler); },
  onWakeWordActivation: (listener) => {
    const handler = (_event, payload) => listener(Object.freeze({
      source: 'local-windows-sapi',
      detectedAt: Number.isFinite(Number(payload?.detectedAt)) ? Number(payload.detectedAt) : Date.now()
    }));
    ipcRenderer.on(CHANNELS.wakeWordActivation, handler);
    return () => ipcRenderer.removeListener(CHANNELS.wakeWordActivation, handler);
  }
});

// #endregion
