import type { Metadata } from "next";
import { Bug, CheckCircle2, Database, EyeOff, FileKey2, Fingerprint, KeyRound, LockKeyhole, PackageCheck, ShieldCheck, Siren, TimerReset } from "lucide-react";
import { SiteFooter } from "../components/SiteChrome";
import { HardNavigationLink } from "../components/HardNavigationLink";

export const metadata: Metadata = { title: "NexusNXS Trust Center — Sicurezza verificabile", description: "Architettura, privacy, distribuzione e segnalazione responsabile di NexusNXS.", alternates:{canonical:"/security"}, openGraph: { title: "NexusNXS Trust Center", description: "Sicurezza verificabile, non promesse.", images: [] }, twitter: { title: "NexusNXS Trust Center", description: "Sicurezza verificabile, non promesse.", images: [] } };
const controls = [{ Icon: Database, title: "Dati controllati", text: "La cronologia completa resta nelle app; richiesta, allegati scelti e contesto recente raggiungono il Core tramite HTTPS." }, { Icon: KeyRound, title: "Identità revocabile", text: "Token limitati per funzione, pairing monouso e revoca immediata dei dispositivi." }, { Icon: EyeOff, title: "Telemetria minima", text: "Nessun contenuto personale nella diagnostica e nessun tracking pubblicitario invasivo." }, { Icon: PackageCheck, title: "Distribuzione controllata", text: "La pubblicazione richiede versione, impronta SHA-256 e firma verificata; finché un controllo manca, il download resta privato." }, { Icon: LockKeyhole, title: "Confini di rete", text: "Il servizio AI pubblico è separato dagli strumenti e dalla knowledge privata di amministrazione." }, { Icon: Fingerprint, title: "Consenso esplicito", text: "Le azioni sensibili richiedono autorizzazioni comprensibili, circoscritte e revocabili." }];

export default function Security() { return <main className="inner-page" id="main-content">
  <section className="trust-hero"><div><p className="eyebrow"><ShieldCheck size={14} /> NEXUSNXS TRUST CENTER</p><h1>La sicurezza è<br /><em>un comportamento.</em></h1><p>Riduciamo il rischio con meno dati, confini di rete espliciti, distribuzioni controllate e verifiche ripetibili. Qui distinguiamo ciò che è attivo da ciò che deve ancora essere completato.</p></div><div className="trust-seal"><ShieldCheck /><strong>SECURITY<br />BY DESIGN</strong><span>ARCHITECTURE · DISTRIBUTION · RECOVERY</span></div></section>
  <section className="security-summary" aria-label="Stato dei controlli"><div><CheckCircle2 /><span>ATTIVO</span><strong>Cifratura in transito</strong></div><div><CheckCircle2 /><span>ATTIVO</span><strong>Amministrazione privata</strong></div><div className="pending"><TimerReset /><span>IN COMPLETAMENTO</span><strong>Firma delle release</strong></div></section>
  <section className="control-grid">{controls.map(({ Icon, title, text }, i) => <article key={title}><span>0{i + 1}</span><Icon strokeWidth={1.25} /><h2>{title}</h2><p>{text}</p></article>)}</section>
  <section className="data-flow" id="privacy"><div><p className="section-label">/ DATA FLOW</p><h2>Semplice da capire.<br /><em>Difficile da compromettere.</em></h2></div><div className="flow-line"><span>CLIENT</span><i /><span>API CIFRATA</span><i /><span>NEXUSNXS CORE</span><i /><span>RISPOSTA</span></div><ul><li><CheckCircle2 /> Il database non è accessibile direttamente dalle app.</li><li><CheckCircle2 /> Le funzioni amministrative non sono esposte pubblicamente.</li><li><CheckCircle2 /> Il servizio pubblico rifiuta strumenti e knowledge personali.</li></ul></section>
  <section className="security-policies"><article><FileKey2 /><p className="section-label">DISTRIBUZIONE</p><h2>Release verificabili</h2><p>Stato della firma, impronta SHA-256, requisiti e avvisi vengono pubblicati come un unico set. Le Preview non firmate sono sempre indicate esplicitamente.</p><HardNavigationLink href="/downloads">Vedi lo stato delle release →</HardNavigationLink></article><article><Siren /><p className="section-label">DIVULGAZIONE</p><h2>Segnalazione responsabile</h2><p>Confermiamo la ricezione delle segnalazioni e condividiamo aggiornamenti durante analisi e correzione, senza richiedere dati personali non necessari.</p><HardNavigationLink href="/.well-known/security.txt">Apri security.txt →</HardNavigationLink></article></section>
  <section className="report-band"><Bug /><div><p className="section-label">RESPONSIBLE DISCLOSURE</p><h2>Hai trovato una vulnerabilità?</h2><p>Descrivi impatto e passaggi di riproduzione. Non includere credenziali, dati personali o contenuti di terzi.</p></div><a className="primary-button" href="mailto:security@nexusnxs.com?subject=Segnalazione%20sicurezza%20NexusNXS">security@nexusnxs.com</a></section>
  <SiteFooter />
</main>; }
